import { useEffect, useRef, type FormEvent } from "react";
import { CalendarDays, Clock3, Compass, MapPin, Settings2, Sparkles } from "lucide-react";
import { Button } from "./Button";

export interface FormState { name:string; gender:"male"|"female"; birthDateTime:string; calendar:"solar"|"lunar"; timezone:string; locationName:string; longitude:string; trueSolarTime:"none"|"longitude"|"apparent"; sect:1|2; }
interface InputPanelProps { form:FormState; error?:string; onChange:(next:FormState)=>void; onSubmit:()=>void; }
const timePeriods=[{label:"子",range:"23:00–00:59",value:"23:00"},{label:"丑",range:"01:00–02:59",value:"01:00"},{label:"寅",range:"03:00–04:59",value:"03:00"},{label:"卯",range:"05:00–06:59",value:"05:00"},{label:"辰",range:"07:00–08:59",value:"07:00"},{label:"巳",range:"09:00–10:59",value:"09:00"},{label:"午",range:"11:00–12:59",value:"11:00"},{label:"未",range:"13:00–14:59",value:"13:00"},{label:"申",range:"15:00–16:59",value:"15:00"},{label:"酉",range:"17:00–18:59",value:"17:00"},{label:"戌",range:"19:00–20:59",value:"19:00"},{label:"亥",range:"21:00–22:59",value:"21:00"}];
const years=Array.from({length:201},(_,i)=>1900+i), months=Array.from({length:12},(_,i)=>i+1), hours=Array.from({length:24},(_,i)=>i), minutes=Array.from({length:60},(_,i)=>i);
const locations=[{name:"北京市 东城区",longitude:"116.42"},{name:"上海市 黄浦区",longitude:"121.49"},{name:"天津市 和平区",longitude:"117.20"},{name:"重庆市 渝中区",longitude:"106.57"},{name:"广州市 越秀区",longitude:"113.27"},{name:"深圳市 福田区",longitude:"114.05"},{name:"杭州市 西湖区",longitude:"120.13"},{name:"南京市 玄武区",longitude:"118.80"},{name:"成都市 锦江区",longitude:"104.08"},{name:"武汉市 武昌区",longitude:"114.32"},{name:"西安市 碑林区",longitude:"108.94"},{name:"长沙市 岳麓区",longitude:"112.93"},{name:"郑州市 金水区",longitude:"113.66"},{name:"沈阳市 和平区",longitude:"123.42"},{name:"哈尔滨市 道里区",longitude:"126.62"},{name:"昆明市 五华区",longitude:"102.71"},{name:"乌鲁木齐市 天山区",longitude:"87.63"},{name:"拉萨市 城关区",longitude:"91.14"},{name:"香港 中西区",longitude:"114.15"},{name:"澳门 花地玛堂区",longitude:"113.55"},{name:"台北市 中正区",longitude:"121.52"}];
function datePart(v:string){return v.split("T")[0]??"";} function timePart(v:string){return v.split("T")[1]?.slice(0,5)??"";} function pad2(v:number|string){return String(v).padStart(2,"0");} function daysInMonth(y:number,m:number){return new Date(y,m,0).getDate();}
function dateParts(v:string){const [y="",m="",d=""]=datePart(v).split("-");return{year:Number(y)||new Date().getFullYear(),month:Number(m)||1,day:Number(d)||1};}
function WheelColumn({label,options,renderOption=String,value,onChange}:{label:string;options:number[];renderOption?:(v:number)=>string;value:number;onChange:(v:number)=>void}){const selectedIndex=Math.max(0,options.indexOf(value));const activeRef=useRef<HTMLButtonElement|null>(null),listRef=useRef<HTMLDivElement|null>(null);useEffect(()=>{if(activeRef.current&&listRef.current)listRef.current.scrollTop=activeRef.current.offsetTop-listRef.current.clientHeight/2+activeRef.current.clientHeight/2;},[value]);return <div className="wheel-column"><span>{label}</span><select value={value} onChange={e=>onChange(Number(e.target.value))} aria-label={label}>{options.map(o=><option value={o} key={o}>{renderOption(o)}</option>)}</select><div className="wheel-list" role="listbox" aria-label={`${label}滚轮`} ref={listRef}>{options.map(o=><button aria-selected={o===value} className={o===value?"active":""} key={o} onClick={()=>onChange(o)} ref={o===value?activeRef:undefined} type="button">{renderOption(o)}</button>)}</div><div className="wheel-stepper"><button type="button" onClick={()=>onChange(options[Math.max(0,selectedIndex-1)])}>−</button><button type="button" onClick={()=>onChange(options[Math.min(options.length-1,selectedIndex+1)])}>＋</button></div></div>}
export function InputPanel({error,form,onChange,onSubmit}:InputPanelProps){const selectedDate=dateParts(form.birthDateTime),selectedTime=timePart(form.birthDateTime),selectedHour=Number(selectedTime.slice(0,2))||0,selectedMinute=Number(selectedTime.slice(3,5))||0,dayOptions=Array.from({length:daysInMonth(selectedDate.year,selectedDate.month)},(_,i)=>i+1);function patch<K extends keyof FormState>(key:K,value:FormState[K]){onChange({...form,[key]:value});} function patchDateTime(d:string,t:string){patch("birthDateTime",d?`${d}T${t||"00:00"}`:"");} function patchDatePart(part:"year"|"month"|"day",value:number){const next={...selectedDate,[part]:value};patchDateTime(`${next.year}-${pad2(next.month)}-${pad2(Math.min(next.day,daysInMonth(next.year,next.month)))}`,selectedTime||"00:00");} function patchTimePart(part:"hour"|"minute",value:number){patchDateTime(datePart(form.birthDateTime)||`${selectedDate.year}-${pad2(selectedDate.month)}-${pad2(selectedDate.day)}`,`${pad2(part==="hour"?value:selectedHour)}:${pad2(part==="minute"?value:selectedMinute)}`);} function selectLocation(name:string){const l=locations.find(x=>x.name===name);onChange({...form,locationName:name,longitude:l?.longitude??form.longitude});} function submit(e:FormEvent){e.preventDefault();onSubmit();}
return <form className="panel input-panel input-panel-v2" onSubmit={submit}>
<div className="panel-heading"><div><p className="eyeline">出生资料</p><h2>建立命盘</h2><span className="panel-subtitle">第一次使用只填基本资料即可；专业时间口径保持默认也能完成排盘。</span></div><Compass className="input-heading-icon" size={22}/></div>
<label className="field"><span>怎么称呼这张命盘？ <small className="field-optional">可选</small></span><input placeholder="例如：自己 / 小明 / A" value={form.name} onChange={e=>patch("name",e.target.value)}/></label>
<div className="compact-field-grid"><div><div className="field-label-row"><span>性别</span><small>用于大运顺逆与紫微排盘</small></div><div className="segmented two-up" aria-label="性别"><button type="button" className={form.gender==="male"?"active":""} onClick={()=>patch("gender","male")}><strong>男</strong><small>乾造</small></button><button type="button" className={form.gender==="female"?"active":""} onClick={()=>patch("gender","female")}><strong>女</strong><small>坤造</small></button></div></div><label className="field"><span>历法输入</span><select value={form.calendar} onChange={e=>patch("calendar",e.target.value as FormState["calendar"])}><option value="solar">阳历 / 公历</option><option value="lunar">农历 / 阴历（实验）</option></select></label></div>
<div className="date-time-grid"><label className="field"><span><CalendarDays size={14}/> 出生日期</span><input required type="date" value={datePart(form.birthDateTime)} onChange={e=>patchDateTime(e.target.value,selectedTime||"00:00")}/></label><label className="field"><span><Clock3 size={14}/> 出生时间</span><input required type="time" step="60" value={selectedTime} onChange={e=>patchDateTime(datePart(form.birthDateTime),e.target.value)}/><small className="field-helper">只记得“子时/午时”？可展开下面的十二时辰快捷选择。</small></label></div>
<details className="precision-picker"><summary><span><Settings2 size={15}/> 只记得传统时辰 / 需要精确调时？</span><small>可选</small></summary><div className="precision-content"><div className="wheel-picker date-wheel"><WheelColumn label="年" options={years} value={selectedDate.year} onChange={v=>patchDatePart("year",v)} renderOption={v=>`${v}年`}/><WheelColumn label="月" options={months} value={selectedDate.month} onChange={v=>patchDatePart("month",v)} renderOption={v=>`${v}月`}/><WheelColumn label="日" options={dayOptions} value={selectedDate.day} onChange={v=>patchDatePart("day",v)} renderOption={v=>`${v}日`}/></div><div className="wheel-picker time-wheel"><WheelColumn label="时" options={hours} value={selectedHour} onChange={v=>patchTimePart("hour",v)} renderOption={v=>`${pad2(v)}点`}/><WheelColumn label="分" options={minutes} value={selectedMinute} onChange={v=>patchTimePart("minute",v)} renderOption={v=>`${pad2(v)}分`}/></div><div className="time-period-grid">{timePeriods.map(p=><button className={selectedTime===p.value?"active":""} key={p.label} onClick={()=>patchDateTime(datePart(form.birthDateTime)||`${selectedDate.year}-${pad2(selectedDate.month)}-${pad2(selectedDate.day)}`,p.value)} type="button"><strong>{p.label}</strong><span>{p.range}</span></button>)}</div></div></details>
<details className="advanced-options time-settings-v3" open={form.trueSolarTime!=="none"}><summary><span>高级时间设置</span><small>{form.trueSolarTime==="none"?"当前：标准时（默认推荐）":form.trueSolarTime==="longitude"?"当前：地方平太阳时":"当前：真太阳时"}</small></summary><div className="advanced-inner"><p className="advanced-explainer">不确定怎么选时，保持“标准时”即可。只有你明确需要经度修正或真太阳时时再修改。</p><div className="time-method-grid" aria-label="时间口径"><button type="button" className={form.trueSolarTime==="none"?"active":""} onClick={()=>patch("trueSolarTime","none")}><strong>标准时</strong><small>默认 · 钟表时间</small></button><button type="button" className={form.trueSolarTime==="longitude"?"active":""} onClick={()=>patch("trueSolarTime","longitude")}><strong>地方平太阳时</strong><small>经度修正</small></button><button type="button" className={form.trueSolarTime==="apparent"?"active":""} onClick={()=>patch("trueSolarTime","apparent")}><strong>真太阳时</strong><small>经度 + 均时差</small></button></div>{form.trueSolarTime!=="none"?<div className="solar-location"><label className="field"><span>出生地</span><input list="birthplace-options" placeholder="例如：烟台市 海阳市" value={form.locationName} onChange={e=>selectLocation(e.target.value)}/><datalist id="birthplace-options">{locations.map(l=><option value={l.name} key={l.name}/>)}</datalist></label><label className="field"><span>经度</span><input inputMode="decimal" placeholder="例如 121.17" value={form.longitude} onChange={e=>patch("longitude",e.target.value)}/></label><div className="input-note compact"><MapPin size={15}/>经度可手动填写，最终资料会保留修正量。</div></div>:null}</div></details>
<details className="advanced-options"><summary><span>专业排盘口径</span><small>绝大多数用户无需修改</small></summary><div className="advanced-inner"><label className="field"><span>子初换日 / 起运 sect</span><select value={form.sect} onChange={e=>patch("sect",Number(e.target.value) as 1|2)}><option value={1}>Sect 1 · 子初换日</option><option value={2}>Sect 2 · 子正换日</option></select></label><p>这个选项主要影响夜子时附近的日柱与起运结果；如果你没有明确门派要求，保持默认。</p></div></details>
<Button type="submit" variant="primary" className="generate-chart-button"><Sparkles size={17}/>生成八字 + 紫微命盘</Button>{error?<p className="form-error">{error}</p>:null}<div className="input-note"><CalendarDays size={16}/>计算与历史记录都在当前浏览器本地完成；生成后可一键复制给你喜欢的 AI。</div>
</form>}
